#!/bin/sh

filename=`date +"%Y%m%d%I%M%S"`
mkdir -p /tmp/selfie/
`/usr/local/bin/imagesnap -q -w 3 /tmp/selfie/$filename.jpg`
count=`/Users/henteko/.anyenv/envs/rbenv/shims/face_counter /tmp/selfie/$filename.jpg`
if [ $count -ge 1 ]; then
  `mv /tmp/selfie/$filename.jpg /path/to/google_photos/`
fi
